server:
  port: 8081
spring:
  session:
    store-type: redis
  # 应用名称
  application:
    name: notification-service
security:
  sessions: never

eureka:
  instance:
    # 使用 ip 代替实例名
    prefer-ip-address: true
    # 实例的主机名
    hostname: ${spring.cloud.client.ip-address}
    # 实例的 ID 规则
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
  client:
    serviceUrl:
      # 注册中心地址
      defaultZone: http://${eureka.instance.hostname}:8079/eureka/
logging:
  level:
    # log 级别
    org.springframework.cloud.gateway: debug
    org.springframework.security: debug